version: '3'

tasks:
  # Top-level tasks
  install:
    desc: Install dependencies
    cmds:
      - npm install

  build:
    desc: Build for production
    cmds:
      - npm run build

  preview:
    desc: Preview production build
    cmds:
      - npm run preview

  clean:
    desc: Clean build artifacts and node_modules
    cmds:
      - cmd: rm -rf dist/ node_modules/
        platforms: [linux, darwin]
      - cmd: if exist dist rmdir /s /q dist
        platforms: [windows]
        ignore_error: true
      - cmd: if exist node_modules rmdir /s /q node_modules
        platforms: [windows]
        ignore_error: true

  # Development
  dev:start:
    desc: Start development server
    cmds:
      - npm run dev

  # Docker operations
  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t web .

  docker:run:
    desc: Run Docker container
    cmds:
      - docker run -p 3000:80 web

  # Code quality
  lint:
    desc: Run ESLint (check only)
    cmds:
      - npm run lint

  lint:fix:
    desc: Run ESLint and auto-fix issues
    cmds:
      - npm run lint:fix

  format:
    desc: Format code with Prettier
    cmds:
      - npx prettier --write "src/**/*.{js,vue,json,md}"

  format:check:
    desc: Check code formatting
    cmds:
      - npx prettier --check "src/**/*.{js,vue,json,md}"

  # Security
  security:audit:
    desc: Run npm security audit (high/critical only)
    cmds:
      - npm audit --audit-level=high

  # Linting
  lint:markdown:
    desc: Lint Markdown files
    cmds:
      - npx markdownlint-cli2

  # CI/CD
  ci:all:
    desc: Run all CI checks (format, lint:fix, build, security:audit, lint:markdown)
    cmds:
      - task: format
      - task: lint:fix
      - task: build
      - task: security:audit
      - task: lint:markdown
      - echo "All CI checks passed!"
